# Importing NumPy

In [ ]:
import numpy as np
print(np.__version__)

1.19.5


# Creating an array with NumPy

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is **numpy.ndarray** type.

To create an ndarray, we can pass **a list, tuple or any array-like object** into the array() method, and it will be converted into an ndarray!

In [ ]:
arr2 = np.array((1, 2, 3, 4, 5))
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in Arrays

0-Dimension

In [ ]:
arr3 = np.array(42)
print(arr3)

42


1-Dimension

In [ ]:
print(arr)

[1 2 3 4 5]


2-Dimension

In [ ]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr4)

[[1 2 3]
 [4 5 6]]


3-Dimension

In [ ]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr5)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Checking for number of dimensions

In [ ]:
print(arr3.ndim) # 0-D
print(arr4.ndim) # 2-D
print(arr5.ndim) # 3-D

0
2
3


An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [ ]:
arr6 = np.array([1, 2, 3, 4], ndmin=5)

print(arr6)
print('number of dimensions :', arr6.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array Extraction

In [ ]:
arr7 = np.array([1, 3, 5, 7, 9])
print(arr7[1])

3


In [ ]:
arr8 = np.array([[1, 2, 3], np.array([2, 4, 6])])
print(arr8[0])
print(arr8[0, 1])
print(arr8[-1, -2])

[1 2 3]
2
4


In [ ]:
arr8[0, 1:3:1]

array([2, 3])

# Data Types in NumPy

By default Python have these data types:

* string - used to represent text data, the text is given under quote marks. e.g. "ABCD"
* integer - used to represent integer numbers. e.g. -1, -2, -3
* float - used to represent real numbers. e.g. 1.2, 42.42
* boolean - used to represent True or False.
* complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [ ]:
arr9 = np.array([1, 2, 3, 4])
print(arr9.dtype)

arr10 = np.array(['apple', 'banana', 'cherry'])
print(arr10.dtype)

int64
<U6


For i, u, f, S and U we can define size as well.

In [ ]:
arr11 = np.array([1, 2, 3, 6], dtype='i4')

print(arr11)
print(arr11.dtype)

[1 2 3 6]
int32


In [ ]:
#arr12 = np.array(['a', '2', '3'], dtype='i')

ValueError: ignored

# Type Conversion

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [ ]:
arr13 = np.array([1.1, 2.1, 3.1])
newarr = arr13.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Copy vs View

In [ ]:
arr14 = np.array([1, 2, 3, 4, 5])
x = arr14.copy()
arr14[0] = 42

print(arr14)
print(x)

In [ ]:
arr15 = np.array([1, 2, 3, 4, 5])
y = arr15.view()
arr15[0] = 42

print(arr15)
print(y)

y[0] = 31
print(arr15)
print(y)

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [ ]:
arr14 = np.array([1, 2, 3, 4, 5])
x = arr14.copy()

print(x.base)
print(y.base)

# Shape and Reshape

In [ ]:
arr16 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr16.shape)
newarr = arr16.reshape(4, 3) # change to (2, 3, 2) then (3, 5)
print(newarr)
print(newarr.shape)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [ ]:
arr17 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr17.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

**Note:** We can not pass -1 to more than one dimension.

In [ ]:
arr18 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr18.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
arr19 = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr19.reshape(-1)
print(newarr)
newarr2 = arr19.ravel()
print(newarr2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


**Note:** There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

# Iterating Arrays

In [ ]:
# Iterating an element is just like a list, unless we had another function that does this.
arr20 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr20:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr21 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr21):
  print(x)

1
2
3
4
5
6
7
8


We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [ ]:
arr22 = np.array([1, 2, 3])

for x in np.nditer(arr22, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [ ]:
arr23 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr23[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
arr24 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr24):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining Arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting Arrays

Splitting is reverse operation of joining.

Joining merges multiple arrays into one and splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4) # arr % 2 == 1
print(x)

(array([3, 5, 6]),)


There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7) # add parameter side = 'right'
print(x)

2


In [ ]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


# Sorting Array

In [ ]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]


# Filtering an Array

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [ ]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [ ]:
# How to filter odd values?
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


# Misc

In [ ]:
# Placeholders
a = np.zeros((3,4))
b = np.ones((2,3,4))
c = np.arange(10,25,5)
d = np.linspace(0,2,9)
e = np.full((2,2),7)
f = np.eye(5)
g = np.random.random((2,4))
h = np.empty((3,2))

print(h)

[[9.9e-324 1.5e-323]
 [2.0e-323 0.0e+000]
 [4.9e-324 2.5e-323]]


In [ ]:
x1 = np.array([1,2,3])
x2 = np.array([1,3,5])

print(x1+x2)
print(x1-x2)
print(np.add(x1,x2))
print(np.multiply(x1,x2))
print(np.exp(x1))
print(np.sqrt(x1))
print(np.sin(x1)) # cos, log

[2 5 8]
[ 0 -1 -2]
[2 5 8]
[ 1  6 15]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]


In [ ]:
x1.dot(x2)

22

In [ ]:
x1.sum() # min, max, cumsum, mean, median, corrcoef

6

In [ ]:
np.std(x2)

1.632993161855452

In [ ]:
np.transpose(x2) # or x2.T

array([1, 3, 5])

# Good job! You have finished our simple NumPy tutorial!